[workspace]
resolver = "2"
members = [
    "graphwalker-core",
    "graphwalker-dsl",
    "graphwalker-io",
    "graphwalker-model-checker",
    "graphwalker-cli",
    "graphwalker-restful",
    "graphwalker-studio",
    "graphwalker-mcp",
    "graphwalker-service",
]

[workspace.package]
rust-version = "1.88"
repository = "https://github.com/KristianKarl/graphwalker-rs"
homepage = "https://graphwalker.github.io/graphwalker-rs/"
documentation = "https://graphwalker.github.io/graphwalker-rs/"
