[package]
name = "graph"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.188", features = ["derive", "rc"] }
serde_derive = "1.0.188"
serde_with = "3.3.0"
log = "0.4.20"

[dev_dependencies]
serde_json = "1.0.107"
serde_with = "3.3.0"
pretty_assertions = "1.4.0"