[package]
name = "io"
version = "0.1.0"
edition = "2021"


[dependencies]
graph = { path = "../graph" }
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

[dev_dependencies]
pretty_assertions = "1.4.0"
